name: Node CI

on: [push]

jobs:
  build:

    name: Build, lint & test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Read .nvmrc
      run: echo ::set-output name=nvmrc::$(cat .nvmrc)
      id: nvm

    - name: Use Node.js "${{ steps.nvm.outputs.nvmrc }}"
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.nvmrc }}"

    - name: npm install, lint, build, and test
      run: |
        npm ci
        npm run lint --if-present
        npm run build --if-present
        npm test --if-present
      env:
        CI: true
